### PR TITLE
Ability for Crafty Crate to combine damaged items for repair

### PR DESCRIPTION
**Pull request by AlexSocol**
Crafty crate as well as a lot of other autocrafting methods (World Interaction Upgrade, EIO Crafter, Auto Crafting Bench, Molecular Assembler, etc.) I've tested were not able to combine two damaged items to repair them, so I've added this feature to Crafty Crate.

### CODE REVIEW

**Comment by Alastors** [comment]
Personally I'm fine with it but I'd like Combuster's thoughts first

**Review by Alastors — DISMISSED** [review]
Putting a block on merging until combuster reviews, feel free to remove once that happens

**Review by combusterf — APPROVED** [review]

**Review by Alastors — APPROVED** [review]

**Comment by combusterf** [comment]
This might affect balance however

**Comment by Alastors** [comment]
Nah it's prolly fine

**Comment by combusterf** [comment]
Spoke with Dream about it, there seems to be no reason why it shouldn't be allowed.

**Pull request merged**
