### PR TITLE
backported item filter for Rannuncarpus

### PR DESCRIPTION
**Pull request by shadoxxhd**
might be useful to have in the main Botania version for 1.7.10

(you could also have a look at https://github.com/shadoxxhd/Botania/releases/tag/1.11.5-c - some of these changes might or might not also be of interest)

### CODE REVIEW

**Comment by Dream-Master** [comment]
Sure you can make more prs if you like . We backport much stuff from new ender io version as well @shadoxxhd

**Comment by chochem** [comment]
@Dream-Master what they linked is not newer botania. just their personal random buff fork.

**Comment by Dream-Master** [comment]
Ah it sounds to me that it is stuff from newer botania version

**Comment by chochem** [comment]
rannuncarpus filter is. the rest is not.

**Comment by shadoxxhd** [comment]
I assumed you meant I should just make a PR to "see what sticks" from my preference changes; I can close the other PR if that is not how you usually review random suggestions.

**Comment by Dream-Master** [comment]
> I assumed you meant I should just make a PR to "see what sticks" from my preference changes; I can close the other PR if that is not how you usually review random suggestions/ideas/preferences.

Let the pr open we can discuss it and see what we pull in.

**Review by serenibyss — APPROVED** [review]

**Pull request merged**
