### PR TITLE
Fix irrelevant flowers show up in NEI

### PR DESCRIPTION
**Pull request by miozune**

### CODE REVIEW

**Comment by combusterf** [comment]
This seems to have broken the NEI integration altogether. I can't see recipes and usages for basic items like mana quartz and prismarine with these changes applied.

**Comment by miozune** [comment]
@combusterf I can see recipes in both runClient and full pack. If you are in the full pack, update NEI to [2.2.7-GTNH](https://github.com/GTNewHorizons/NotEnoughItems/releases/tag/2.2.7-GTNH) or above.

**Review by Dream-Master — APPROVED** [review]

**Comment by combusterf** [comment]
That still means that you broke Botania for everyone else who doesn't have this very tailored NEI version.

I also fail to see from your description what was actually supposedly broken in the first place.

**Comment by miozune** [comment]
- Botania stores flower type in NBT.
- Most of the mods use `areStacksSameTypeCrafting`, which does not take account of NBT.

Thus, when you look up recipe for specific Botania flower, you will also see other flowers show up. This PR fixes it.

And specified NEI version #8

**Pull request merged**
